openapi: 3.1.0
info:
  title: GHCR Browser API
  version: 0.1.0
  description: Minimal API for listing GHCR image tag names (MVP)
servers:
  - url: /api
paths:
  /images/{owner}/{image}/tags:
    get:
       summary: List tags for an image
      description: Returns tag names for a given image. No pagination or metadata in MVP.
      operationId: listImageTags
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: image
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tag list
          content:
            application/json:
              schema:
                type: object
                properties:
                  tags:
                    type: array
                    items:
                      type: string
                required: [tags]
        '400':
          description: Invalid input format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Repository not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /health:
    get:
      summary: Health probe
      operationId: health
      responses:
        '200':
          description: Service healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  uptimeSeconds:
                    type: integer
                    minimum: 0
                required: [status, uptimeSeconds]
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          enum: [InvalidFormat, NotFound]
        message:
          type: string
      required: [code, message]
